/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\big_electric_pole\scene.gltf -o .\src\Components\Electric_line.jsx -r public 
Author: ustoopia (https://sketchfab.com/ustoopia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-pole-341079cf3c584b5cbb920da0cc43f13f
Title: Electric Pole
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Electric_pole(props) {
  const { nodes, materials } = useGLTF('/models/big_electric_pole/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 12.278, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Stainless_Steel} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Metal_04} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Brushed_metal} position={[0, -12.278, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/big_electric_pole/scene.gltf')
