/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\grass_variations\scene.gltf -o .\src\Components\Grass.jsx -r public 
Author: RBG_illustrations (https://sketchfab.com/RBG_illustrations)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-variations-c84573687bf14f89938002df4ca0e696
Title: Grass Variations
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Grass(props) {
  const { nodes, materials } = useGLTF("/models/grass_variations/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.grass_varien_4_grass_0.geometry}
        material={materials.grass}
        position={[0, 0, 164.634]}
      />
      <mesh
        geometry={nodes.grass_variant_1_grass1_0.geometry}
        material={materials.grass1}
        position={[0, 0, -116.897]}
      />
      <mesh
        geometry={nodes.grass_varient_2_grass2_0.geometry}
        material={materials.grass2}
      />
      <mesh
        geometry={nodes.grass_varient_3_grass3_0.geometry}
        material={materials.grass3}
        position={[0, 0, 87.645]}
      />
    </group>
  );
}

useGLTF.preload("/models/grass_variations/scene.gltf");
